### ISSUE TITLE
Settings parameters won't replace old values when saved; ILIAS then picks the first best parameter value

### ISSUE THREAD

**Issue by Rillke** [kyro46/ilIRTEvaluations#1]
Settings parameters won't replace old values when saved; ILIAS then picks the first best parameter value

![image](https://user-images.githubusercontent.com/2311611/209368921-d91e15ad-c310-4b04-925e-3cd4a94a443a.png)

I was updating the URL to a HTTPS one and wondered why the settings from the settings GUI were not applied.

![image](https://user-images.githubusercontent.com/2311611/209369041-149da5aa-77d5-4608-8fed-2d8c1059b327.png)

**Comment by Rillke** [comment]
Addtionally I had to clean out the cache table: `TRUNCATE TABLE ilias.etstat_cache;`

**Comment by Rillke** [comment]
CORS headers are required for the R console to work if hosted on a different domain.

**Comment by kyro46** [comment]
I also see 6 instances of the variables from ilExteEvalTestCIC in your picture which are not part of the IRT-Plugin. The IRT-Plugin uses the mechanism to create and change parameters provided by the base plugin etstat and I can't reproduce the shown behaviour.

The cache is a inherent mechanism of etstat too and stores evaluations to prevent costly recalculation until settings or content of a test change. What was the problem here?

I'll have a look at cors. Until now only used it on different IPs.

**Comment by Rillke** [comment]
>  and I can't reproduce the shown behaviour.

okay. I truncated the table and saved the settings again so for now, this is not an issue right now. The question remains if it's worth to debug this in our instance since we still run this terribly outdated version of ILIAS.

> The cache is a inherent mechanism of etstat too and stores evaluations to prevent costly recalculation until settings or content of a test change. What was the problem here?

In spite of having the correct value in ststat_parameter_name='server', the browser tried to contact the previously saved server when opening the interactive R console. (i.e. replacing `{SERVER}` in the template with an outdated value).

> I'll have a look at cors. Until now only used it on different IPs.

Thanks. The CORS-Issue is a non-issue. The R-Server already sets required CORS headers. Only if no response at all comes through, the browser complains about missing CORS headers...
